item_dict= {
    "石": "stone",
    "花崗岩": "granite",
    "磨かれた花崗岩": "polished_granite",
    "閃緑岩": "diorite",
    "磨かれた閃緑岩": "polished_diorite",
    "安山岩": "andesite",
    "磨かれた安山岩": "polished_andesite",
    "草ブロック": "grass_block",
    "土": "dirt",
    "粗い土": "coarse_dirt",
    "ポドゾル": "podzol",
    "丸石": "cobblestone",
    "オークの板材": "oak_planks",
    "トウヒの板材": "spruce_planks",
    "シラカバの板材": "birch_planks",
    "ジャングルの板材": "jungle_planks",
    "アカシアの板材": "acacia_planks",
    "ダークオークの板材": "dark_oak_planks",
    "マングローブの板材": "mangrove_planks",
    "サクラの板材": "cherry_planks",
    "岩盤": "bedrock",
    "砂": "sand",
    "赤い砂": "red_sand",
    "砂利": "gravel",
    "石炭鉱石": "coal_ore",
    "鉄鉱石": "iron_ore",
    "銅鉱石": "copper_ore",
    "金鉱石": "gold_ore",
    "レッドストーン鉱石": "redstone_ore",
    "エメラルド鉱石": "emerald_ore",
    "ラピスラズリ鉱石": "lapis_ore",
    "ダイヤモンド鉱石": "diamond_ore",
    "ネザー金鉱石": "nether_gold_ore",
    "ネザークォーツ鉱石": "nether_quartz_ore",
    "古代の残骸": "ancient_debris",
    "石炭ブロック": "coal_block",
    "鉄ブロック": "iron_block",
    "銅ブロック": "copper_block",
    "金ブロック": "gold_block",
    "エメラルドブロック": "emerald_block",
    "ラピスラズリブロック": "lapis_block",
    "ダイヤモンドブロック": "diamond_block",
    "ネザライトブロック": "netherite_block",
    "オークの原木": "oak_log",
    "トウヒの原木": "spruce_log",
    "シラカバの原木": "birch_log",
    "ジャングルの原木": "jungle_log",
    "アカシアの原木": "acacia_log",
    "ダークオークの原木": "dark_oak_log",
    "マングローブの原木": "mangrove_log",
    "サクラの原木": "cherry_log",
    "ガラス": "glass",
    "白色の羊毛": "white_wool",
    "橙色の羊毛": "orange_wool",
    "赤色の羊毛": "red_wool",
    "青色の羊毛": "blue_wool",
    "緑色の羊毛": "green_wool",
    "黒色の羊毛": "black_wool",
    "レンガ": "bricks",
    "本棚": "bookshelf",
    "黒曜石": "obsidian",
    "松明": "torch",
    "作業台": "crafting_table",
    "かまど": "furnace",
    "チェスト": "chest",
    "TNT": "tnt",
    "はしご": "ladder",
    "レバー": "lever",
    "レッドストーントーチ": "redstone_torch",
    "エンチャントテーブル": "enchanting_table",
    "エンダーチェスト": "ender_chest",
    "ビーコン": "beacon",
    "金床": "anvil",
    "ホッパー": "hopper",
    "スライムブロック": "slime_block",
    "ハチミツブロック": "honey_block",
    "観察者": "observer",
    "ピストン": "piston",
    "粘着ピストン": "sticky_piston",
    "ディスペンサー": "dispenser",
    "ドロッパー": "dropper",
    "リピーター": "repeater",
    "コンパレーター": "comparator",
}

item_name = input("調べるアイテムの名前")
item_count = input("何個欲しいですか？")
command_name = ""
if item_name in item_dict.keys():
    command_name = item_dict[item_name]
else:
    print("not item")
command_code = f"/give @p {command_name} {item_count}"
print(command_code)